### ISSUE TITLE
JCE MediaBox 2.1.0 Size of Pop-Up Window

### ISSUE THREAD

**Issue by ChristineWk** [widgetfactory/jce-mediabox#5]
**Describe the bug**

As soon as you link a post, the size of the pop-up window is only correctly displayed with an aspect ratio of 4: 3 (WxH).
(reported & confirmed in german forum). 

The width is always displayed correctly, regardless of the aspect ratio.

**Comment by ryandemmer** [comment]
What width and height values are you using for the popup?

**Comment by ChristineWk** [comment]
thanks @ryandemmer for investigation. 

Example:

Desktop: Setting 600x400 causes a short correct display (500ms). Then the box is "raised" to the maximum height. The width remains. The box can be closed in a conventional manner.

Mobile: The box is displayed over the entire area. There is no icon to close and you can no longer click next to the box.

**Comment by ChristineWk** [comment]
Hi Ryan,
are there any news about?
Thanks

**Comment by ryandemmer** [comment]
I am investigating the issue and will post a fix when the bug is confirmed and resolved.

Please note that **Issues** is not for product support, but to post bug reports. For direct product support, please post in the JCE Support Forum - https://www.joomlacontenteditor.net/support/forum

**Comment by ryandemmer** [comment]
Possible fix in commit - https://github.com/widgetfactory/jce-mediabox/commit/71118ca94c0215f700df7fa054e726c6184321fe

A test beta is available here - https://github.com/widgetfactory/jce-mediabox/releases/tag/2.1.1-beta-2

**Comment by ChristineWk** [comment]
> 
> 
> I am investigating the issue and will post a fix when the bug is confirmed and resolved.
> 
> Please note that **Issues** is not for product support, but to post bug reports. For direct product support, please post in the JCE Support Forum - https://www.joomlacontenteditor.net/support/forum

 
OK, Thanks.
... that's what I did. See: _Thank you to everyone who submitted bug reports and tested development versions. If you find any more issues please submit them on the forum or on github._

 So, I need subscription, correct? And then to repeat above issue?

Just saw your new comment - hv to read.

**Comment by ChristineWk** [comment]
The test beta zip I could download or changing the possible fix accordingly via FTP?
Because I'm working usually with "Normal Patchtester"

**Comment by ryandemmer** [comment]
Just download the beta from here - https://github.com/widgetfactory/jce-mediabox/releases/tag/2.1.1-beta-2 - and install with the Joomla installer.

**Comment by ChristineWk** [comment]
OK, will do so .... thanks.

**Comment by anka56** [comment]
The beta 2 solved the problem.

**Comment by ChristineWk** [comment]
Tested also, confirm. Thanks @anka56 
OT: Just wanted to ask for in forum :-)

**Comment by ChristineWk** [comment]
The topic creator from Joomla forum, has also tested successfully.

**Comment by ryandemmer** [comment]
Thank you
